name: Create Staging Tag

on:
  workflow_dispatch:
    inputs:
      target_branch_or_hash:
        type: string
        required: true
        default: origin/dev
        description: "タグを作成する対象のブランチまたはコミットハッシュ"

jobs:
  create-staging-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Staging Tag
        run: ./script/create-staging-tag.sh ${{ env.TARGET_BRANCH_OR_HASH }}
        env:
          TARGET_BRANCH_OR_HASH: ${{ inputs.target_branch_or_hash }}
      - name: Set up Git user information
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Push the tag to the remote repository
        run: git push origin ${{ env.TARGET_BRANCH_OR_HASH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
